<?php

use Drupal\Core\Cache\CacheableMetadata;
use Drupal\wmpage_cache\Dispatcher;

/**
 * Implements @see hook_cron()
 */
function wmpage_cache_cron(): void
{
    wmpage_cache_cron_purge_expired();
}

/**
 * Purge expired wmpage_cache_cache items.
 */
function wmpage_cache_cron_purge_expired(): void
{
    $ctr = Drupal::getContainer();
    $ctr->get('wmpage_cache.storage')->remove(
        $ctr->get('wmpage_cache.storage')->getExpired(
            $ctr->getParameter('wmpage_cache.purge_per_cron')
        )
    );
}

/**
 * Implements @see hook_cache_flush().
 */
function wmpage_cache_cache_flush(): void
{
    $ctr = \Drupal::getContainer();
    if ($ctr->getParameter('wmpage_cache.flush_on_cache_rebuild')) {
        $ctr->get('wmpage_cache.storage')->flush();
    }
}

/**
 * Implements @see hook_page_attachments().
 */
function wmpage_cache_page_attachments(array &$attachments)
{
    $dispatcher = \Drupal::getContainer()
        ->get('wmpage_cache.dispatcher');

    if (!$dispatcher instanceof Dispatcher) {
        return;
    }

    $dispatcher->getCacheableMetadata()
        ->merge(CacheableMetadata::createFromRenderArray($attachments))
        ->applyTo($attachments);
}
